spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spot_damas # Substitua pelo nome correto do seu banco
    username: yourUsername # Substitua pelo seu usuário
    password: yourPassword # Substitua pela sua senha
    driver-class-name: org.postgresql.Driver

mybatis:
    mapper-locations: classpath*:**/mappers/*Mapper.xml

server:
  port: 8080