spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spot-damas # Substitua pelo nome correto do seu banco
    username: postgres # Substitua pelo seu usuário
    password: postgres # Substitua pela sua senha
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath*:**/mappers/*Mapper.xml

server:
  port: 1000
